### ISSUE TITLE
Docs say envkey-source v2 is installed as 'envkey-source-v2' if envkey1-source is installed, but it isn't

### ISSUE THREAD

**Issue by dbsanfte** [envkey/envkey#36]
Docs say: 

`Note that if you're coming from EnvKey v1 and already have envkey-source v1 installed locally when you install EnvKey v2 and start the EnvKey UI, envkey-source will be installed as envkey-source-v2 instead of envkey-source in order to avoid overwriting the v1 binary and breaking any of your v1-based workflows. You can also use the es alias.`

https://docs-v2.envkey.com/docs/install#download-and-install-the-envkey-ui-and-cli

But if you actually try this, envkey-source v2 just overwrites the envkey v1 binary, and the exact break you describe happens:

https://github.com/envkey/envkey/blob/9dd607552e9d2635a1d6f4c040a0da48d173adc5/public/sdks/envkey-source/install.sh#L110

**Comment by danenania** [comment]
Thanks @dbsanfte. The docs are referring to the UI, which attempts to install `envkey-source` on first run, not the install script to install it independently. 

The thinking is that this issue (overwriting envkey-source) would mainly impact development machines where users would be installing the UI rather than using the envkey-source install script. But I suppose it does make sense to apply the same logic to the script.
