### ISSUE TITLE
Node SDK fails when the app has a pending update

### ISSUE THREAD

**Issue by colvin** [envkey/envkey#47]
We are using the Node SDK (version `2.1.1`), and I've seen several reports from developers in our org where our app suddenly fails to run with an error from `envkey`. They report that after opening the EnvKey app an update prompt appears and, following the update, our app resumes working correctly.

I'll try to come up with less anecdotal information once I can examine the problem in situ.

**Comment by danenania** [comment]
Thanks for reporting this @colvin--we're investigating.

**Comment by danenania** [comment]
This should now be fixed in version 2.1.2 of the Node SDK. Please re-open if you're still seeing any issues after upgrading!

**Comment by slcrider** [comment]
@danenania I'm looking at the fix for this ([0b75ff452323af02f01bab24f1f9ea55977192c1](https://github.com/envkey/envkey/commit/0b75ff452323af02f01bab24f1f9ea55977192c1)) + it looks like this is just a bandaid that doesn't prevent the issue from happening again.  Since this issue was closed, is there a better place to open a request for a fix that truly prevents the issue from happening again?  I'm happy to be corrected if my take is incorrect.

**Comment by danenania** [comment]
@slcrider The issue was that on the backend, we require clients to have a higher version than 2.1.0 due to some crypto performance optimizations that were implemented several months ago and require compatibility from the client.

The node package was self-reporting its version as 2.0.9 to the server, not the actual version, so the fix was simply to update reported version. The way this is written is unfortunately a bit error prone as referencing the version from package.json didn't work in some environments, so the version that gets sent to the server is duplicated, and it wasn't properly updated in the last couple releases.

I hope that makes more sense!

**Comment by slcrider** [comment]
That makes sense, but I think still supports my ask - what does a fix that prevents future version drift look like?

**Comment by danenania** [comment]
Fair enough @slcrider. A test was just added to verify the versions match: https://github.com/envkey/envkey/compare/0b75ff4..3dccea8
